version: '2'
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    command: chmod -R 777 /var/lib/pgadmin
    ports:
      - 8086:80
    volumes:
      - ~/docker-volumes/pgadmin_volume:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=notifications@azilen.com
      - PGADMIN_DEFAULT_PASSWORD=azilen321

