version: '2'
services:
  azilen-notification-postgresql:
    image: postgres:12.3
    container_name: azilen-notification-postgresql
    command: postgres -c 'max_connections=500'
    volumes:
      - ~/docker-volumes/azilen-notification-postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=AzilenNotificationApp
      - POSTGRES_PASSWORD=ds32gXv2qRMK67rC
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
